### ISSUE TITLE
Unhandled errors

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/weathernews#20]
![screenshot from 2018-04-12 05-14-15](https://user-images.githubusercontent.com/28482442/38652841-6a035bd6-3e10-11e8-9b23-d3b5996a366b.png)

I just tried to search something, the app broke.

**Comment by haneenshahwan4** [comment]
we need more time to understand error handling very well,

**Comment by NoureldeanSaed** [comment]
I'll try to see something out next Sunday @haneenshahwan4
