### ISSUE TITLE
What is a router.js

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/weathernews#23]
https://github.com/FACG4/weathernews/blob/a1f5850839d8e811ab1177b2254e1d01a3c57b16/src/router.js#L1-L18

This is ART!!

Very good job, you illustrate what a router is very well.

**Comment by haneenshahwan4** [comment]
thanks Noureldeen , our team and I  worded hard to be creative  and professional  developer

**Comment by NoureldeanSaed** [comment]
@haneenshahwan4 I am glad to hear that someone is actually having sth from the course. Best of luck.
