### ISSUE TITLE
What is handler.js

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/weathernews#26]
https://github.com/FACG4/weathernews/blob/a1f5850839d8e811ab1177b2254e1d01a3c57b16/src/handler.js#L3

This makes me doubt that you know what a handler is, why calling the router.js inside the handler? Do you intend to further route your request? But all in all, it's unused and shouldn't be there.

**Comment by haneenshahwan4** [comment]
its by mistake, we remove it
